### ISSUE TITLE
Privacy policy shows 404 error

### ISSUE THREAD

**Issue by lijogeorgep** [decentralised-dataexchange/bb-consent-android-privacy-dashboard#161]
![Screenshot_2023-10-26-21-47-11-62_8d4c418643cf7cc903277063dd5094c7](https://github.com/decentralised-dataexchange/bb-consent-android-privacy-dashboard/assets/81345608/add0a36a-1bdb-4b30-b6f4-d869e5724715)
![Screenshot_2023-10-26-21-47-00-84_8d4c418643cf7cc903277063dd5094c7](https://github.com/decentralised-dataexchange/bb-consent-android-privacy-dashboard/assets/81345608/e363b9be-4489-4534-a30e-d030825474a3)

**Comment by georgepadayatti** [comment]
> ![Screenshot_2023-10-26-21-47-11-62_8d4c418643cf7cc903277063dd5094c7](https://user-images.githubusercontent.com/81345608/278543489-add0a36a-1bdb-4b30-b6f4-d869e5724715.jpg) ![Screenshot_2023-10-26-21-47-00-84_8d4c418643cf7cc903277063dd5094c7](https://user-images.githubusercontent.com/81345608/278543495-e363b9be-4489-4534-a30e-d030825474a3.jpg)

@josmilan Where is this value coming from ?

![2023-10-30_22-46](https://github.com/decentralised-dataexchange/bb-consent-android-privacy-dashboard/assets/16397960/2111ee92-1e58-4bf0-a56f-ed0335d3de38)
