### ISSUE TITLE
Agreement not updating on selecting Disallow,  if we press the back button 

### ISSUE THREAD

**Issue by kashishmalik** [decentralised-dataexchange/bb-consent-android-privacy-dashboard#196]
Agreement not updating on selecting Disallow,  if we press the back button 

https://github.com/decentralised-dataexchange/bb-consent-android-privacy-dashboard/assets/92527972/016f0f01-0bda-4757-a754-4c93365a8445

**Comment by josmilan** [comment]
There is an error throwing in the API, 

{"errorCode":500,"errorDescription":"Data agreement record for data agreement: 654de9d3850a172890d33e18 and individual id : 65366979db611cb1948aca50 exists"}
