### ISSUE TITLE
On changing the language to Swedish, Data Attributes get cut 

### ISSUE THREAD

**Issue by kashishmalik** [decentralised-dataexchange/bb-consent-android-privacy-dashboard#241]
- [x] Allow and disallow should be translated

- [ ] On changing the language to Swedish, Data Attributes get cut 

![20231121_232209.jpg](https://github.com/decentralised-dataexchange/bb-consent-android-privacy-dashboard/assets/92527972/5260b7e5-7410-4d84-aa94-5716164459d9)

**Comment by josmilan** [comment]
Hii @kashishmalik https://docs.google.com/spreadsheets/d/17eq4hl1lvda4bqCYoL5zb6O_3iAoPfIQNtSfBR5Qy_s/edit#gid=0, in this sheets its the value in Swedish. can you check and update
