### ISSUE TITLE
Opt-in Opt out values are not retained in the app.

### ISSUE THREAD

**Issue by sreelakshmyunnikrishnan** [decentralised-dataexchange/bb-consent-android-privacy-dashboard#250]

**Comment by josmilan** [comment]
@sreelakshmyunnikrishnan how to reproduce this issue?

**Comment by sreelakshmyunnikrishnan** [comment]
@josmilan This issue was in Data4diabetes v2024.2.2 - 34 and the issue was, if we opt-in a DA and the close the app and open again. the value is not retained as Opt-in. 

But now when I tested again this issue seems to be solved and is working in version 34

**Comment by josmilan** [comment]
can we close it? if it is not valid.
