### ISSUE TITLE
Showing user request status for cancelled requests

### ISSUE THREAD

**Issue by josmilan** [decentralised-dataexchange/bb-consent-android-privacy-dashboard#63]
The issue is raised to confirm the flow. 
**Existing flow**

**Android**
If the user request has been canceled then, we won't allow the user to click the user request item and see the status screen. The reason behind this is that, In the API we can get the status of ongoing requests only.

**iOS**
Here we can click any of the user requests, even if it is cancelled. If it is a canceled item, we show it as request canceled in the user request status screen

The above were the existing flow in android and iOS. both are different. Which flow should we follow. Not sure which one is the correct or which should we follow

**Comment by georgepadayatti** [comment]
We can retain the existing behaviours in iOS and Android. In the case of GovStack Consent BB, user requests feature is not relevant iirc.

We can focus on enabling and disabling user requests feature based on configuration defined in SDK.

But I would suggest to keep this question open.

**Comment by lalc** [comment]
Ya. Let's keep the issue open for now
