### ISSUE TITLE
Color difference in User request listing screen

### ISSUE THREAD

**Issue by josmilan** [decentralised-dataexchange/bb-consent-android-privacy-dashboard#69]
In Android and iOS, there is a color difference in the user request listing screen. From the below which one should we follow?

**Android**
![WhatsApp Image 2023-09-28 at 10 42 00](https://github.com/decentralised-dataexchange/bb-consent-android-privacy-dashboard/assets/20550674/280ac5b1-e746-4888-8147-460bd47d2378)

**iOS**
![WhatsApp Image 2023-09-28 at 10 46 24](https://github.com/decentralised-dataexchange/bb-consent-android-privacy-dashboard/assets/20550674/5795f79a-0728-4622-832b-56b93a8a525f)

**Comment by lalc** [comment]
Keep it simple and follow the second one.
